### PR TITLE
Add Prefix for Router

### PR DESCRIPTION
**Pull request by chenly**
fix bug : https://github.com/nuxt-community/tailwindcss-module/issues/459
ref: https://github.com/chenly/tailwindcss-module/commit/d30ac70e83d79bdfc0046ecb200d8468f04a13bd

### CODE REVIEW

**Comment by chenly** [comment]
fix bug: https://github.com/rogden/tailwind-config-viewer/issues/53

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
Tested locally and fix the issue.

**Comment by rogden** [comment]
@Atinux I can add you as a maintainer on the repo and npm package if helpful for now. I use the np package to publish.

**Comment by Atinux** [comment]
Sure thing @rogden :)

**Comment by rogden** [comment]
@Atinux All set. Merged and published as 1.7.1

**Pull request merged**
